-- =====================================================================
-- Shikshaq question bank: schema + data
--
-- Creates bank_papers and bank_questions, their policies, and loads all
-- papers and questions. Safe to run more than once.
--
-- Generated by scripts/generate-bank-sql.ts. Do not hand-edit; regenerate.
-- =====================================================================

set standard_conforming_strings = on;

begin;

create table if not exists public.bank_papers (
  id             text primary key,
  school_raw     text,
  school         text        not null,
  is_board_paper boolean     not null default false,
  year           text,
  exam           text,
  cls            text        not null default 'X',
  subject        text        not null default 'Mathematics',
  board          text        not null default 'ICSE',
  question_count integer     not null default 0,
  marks          integer     not null default 0,
  is_published   boolean     not null default true,
  has_school     boolean     not null default true,
  created_at     timestamptz not null default now()
);

create table if not exists public.bank_questions (
  id       text primary key,
  paper_id text    not null references public.bank_papers (id) on delete cascade,
  ord      integer not null,
  number   text,
  body     text    not null,
  marks    integer,
  chapter  text,
  qtype    text,
  page     integer,
  figure   text,
  options  text[],
  unique (paper_id, ord)
);

create index if not exists bank_questions_paper_idx  on public.bank_questions (paper_id, ord);
create index if not exists bank_papers_school_idx    on public.bank_papers (school);
create index if not exists bank_papers_year_idx      on public.bank_papers (year desc);
create index if not exists bank_papers_published_idx on public.bank_papers (is_published) where is_published;
create index if not exists bank_papers_has_school_idx on public.bank_papers (has_school) where has_school;

alter table public.bank_papers    enable row level security;
alter table public.bank_questions enable row level security;

-- Published papers are the public library: anyone may read, nobody but an
-- admin may write. Dropped first so re-running does not fail on the policy
-- already existing.
drop policy if exists "published papers are public" on public.bank_papers;
create policy "published papers are public"
  on public.bank_papers for select to anon, authenticated
  using (is_published);

drop policy if exists "questions of published papers are public" on public.bank_questions;
create policy "questions of published papers are public"
  on public.bank_questions for select to anon, authenticated
  using (exists (select 1 from public.bank_papers p
                  where p.id = bank_questions.paper_id and p.is_published));

drop policy if exists "admins write papers" on public.bank_papers;
create policy "admins write papers"
  on public.bank_papers for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins write questions" on public.bank_questions;
create policy "admins write questions"
  on public.bank_questions for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

revoke all on public.bank_papers    from anon, authenticated;
revoke all on public.bank_questions from anon, authenticated;
grant select on public.bank_papers    to anon, authenticated;
grant select on public.bank_questions to anon, authenticated;
grant insert, update, delete on public.bank_papers    to authenticated;
grant insert, update, delete on public.bank_questions to authenticated;

commit;
