set standard_conforming_strings = on;
begin;

-- 193 papers
insert into public.bank_papers
  (id, school_raw, school, is_board_paper, year, exam, cls, subject, board,
   question_count, marks, has_school)
values
  ('0c9771', 'ICSE', 'ICSE board paper', true, '2026', 'Board Examination', 'X', 'Mathematics', 'ICSE', 40, 104, false),
  ('4ecffb', 'ICSE', 'ICSE board paper', true, '2026', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 93, false),
  ('da958f', 'ICSE', 'ICSE board paper', true, '2026', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 100, false),
  ('07eae7', 'ICSE', 'ICSE board paper', true, '2026', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 106, false),
  ('e61a0a', 'ICSE', 'ICSE board paper', true, '2026', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 92, false),
  ('4a7cb1', 'Delhi Public School Joka', 'Delhi Public School, Joka', false, '2025-26', 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 48, 81, true),
  ('181264', 'Don Bosco Park Circus', 'Don Bosco School, Park Circus', false, '2025-26', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 83, true),
  ('ccfe7d', 'La Martiniere for Girls', 'La Martiniere for Girls', false, '2025-26', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 36, 92, true),
  ('e833a3', 'Unknown School', 'School not recorded', false, '2025-26', 'Unit Test', 'X', 'Mathematics', 'ICSE', 20, 35, false),
  ('f277e3', 'ICSE', 'ICSE board paper', true, '2025 (2)', 'Board Examination', 'X', 'Mathematics', 'ICSE', 42, 93, false),
  ('55c388', 'CBSE', 'CBSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'CBSE', 134, 302, false),
  ('0a75ef', 'ICSE', 'ICSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 84, false),
  ('84110a', 'ICSE', 'ICSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'ICSE', 40, 78, false),
  ('cf63e8', 'ICSE', 'ICSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'ICSE', 40, 84, false),
  ('7d7bee', 'ICSE', 'ICSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 105, false),
  ('bdb0ef', 'ICSE', 'ICSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 71, false),
  ('3202d9', 'ICSE', 'ICSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 42, false),
  ('b5bc1d', 'ICSE', 'ICSE board paper', true, '2025', 'Board Examination', 'X', 'Mathematics', 'ICSE', 16, 6, false),
  ('673ee3', 'Bhavans Gangabux Kanoria Vidyamandir', 'Bhavan''s Gangabux Kanoria Vidyamandir', false, '2024-25', 'Board Examination', 'X', 'Mathematics', 'Board', 51, 102, true),
  ('a73119', 'C.N.M. School', 'Chandulal Nanavati Vinay Mandir', false, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 42, 107, true),
  ('bb4e80', 'Calcutta Boys School', 'Calcutta Boys’ School', false, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 86, true),
  ('5a3ed4', 'CBSE', 'CBSE board paper', true, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'CBSE', 39, 79, false),
  ('b4ef56', 'CBSE', 'CBSE board paper', true, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'CBSE', 38, 71, false),
  ('c96f2b', 'Delhi Public School Joka', 'Delhi Public School, Joka', false, '2024-25', 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 43, 97, true),
  ('7250a2', 'Delhi Public School Joka', 'Delhi Public School, Joka', false, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 39, 89, true),
  ('bd6cba', 'Delhi Public School Joka', 'Delhi Public School, Joka', false, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 37, 68, true),
  ('f7fc2d', 'Delhi Public School Joka', 'Delhi Public School, Joka', false, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 47, true),
  ('54d4a8', 'La Martiniere for Boys', 'La Martiniere for Boys', false, '2024-25', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 86, true),
  ('ddb4d6', 'CBSE', 'CBSE board paper', true, '2024', 'Board Examination', 'X', 'Mathematics', 'CBSE', 41, 85, false),
  ('23dbf0', 'ICSE', 'ICSE board paper', true, '2024', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 72, false),
  ('665d41', 'ICSE', 'ICSE board paper', true, '2024', 'Board Examination', 'X', 'Mathematics', 'ICSE', 40, 102, false),
  ('fa8623', 'ICSE', 'ICSE board paper', true, '2024', 'Board Examination', 'X', 'Mathematics', 'ICSE', 21, 66, false),
  ('728eae', 'La Martiniere for Boys', 'La Martiniere for Boys', false, '2023-24', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 89, true),
  ('9e2786', 'La Martiniere for Boys', 'La Martiniere for Boys', false, '2023-24', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 8, 20, true),
  ('87ae07', 'ICSE', 'ICSE board paper', true, '2023 (2)', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 103, false),
  ('b0a2a8', 'ICSE', 'ICSE board paper', true, '2023', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 110, false),
  ('471e2c', 'ICSE', 'ICSE board paper', true, '2023', 'Board Examination', 'X', 'Mathematics', 'ICSE', 22, 40, false),
  ('417b04', 'ICSE', 'ICSE board paper', true, '2023', 'Board Examination', 'X', 'Mathematics', 'ICSE', 41, 92, false),
  ('caf50f', 'ICSE', 'ICSE board paper', true, '2023', 'Board Examination', 'X', 'Mathematics', 'ICSE', 40, 84, false),
  ('7416af', 'ICSE', 'ICSE board paper', true, '2023', 'Board Examination', 'X', 'Mathematics', 'ICSE', 30, 87, false),
  ('8f2e73', 'Apex', 'Apex', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('7986c3', 'Ariv X Icse Maths Prelims', 'Ariv', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('ea62b6', 'Asc', 'ASC', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 94, true),
  ('36ddf3', 'Baldwin Girls Hs', 'Baldwin Girls’ High School, Bengaluru', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 42, 99, true),
  ('276cf3', 'Beacon High', 'Beacon High', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('0e91e9', 'Bhaktivedanta Pre', 'Bhaktivedanta Swami Mission School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 38, 100, true),
  ('a30fc0', 'Bhavans Gangabux Kanoria Vidyamandir', 'Bhavan''s Gangabux Kanoria Vidyamandir', false, '2022-23', 'Board Examination', 'X', 'Mathematics', 'Board', 38, 77, true),
  ('9b6d6d', 'Bhavans Gangabux Kanoria Vidyamandir', 'Bhavan''s Gangabux Kanoria Vidyamandir', false, '2022-23', 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 20, 41, true),
  ('6dc917', 'Bhavans Gangabux Kanoria Vidyamandir', 'Bhavan''s Gangabux Kanoria Vidyamandir', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 44, 99, true),
  ('98951c', 'Bhavans Gangabux Kanoria Vidyamandir', 'Bhavan''s Gangabux Kanoria Vidyamandir', false, '2022-23', 'Unit Test', 'X', 'Mathematics', 'ICSE', 15, 43, true),
  ('ad7d57', 'Bhavans Gangabux Kanoria Vidyamandir', 'Bhavan''s Gangabux Kanoria Vidyamandir', false, '2022-23', 'Unit Test', 'X', 'Mathematics', 'ICSE', 14, 40, true),
  ('d8c204', 'Bhuta High School', 'Bhuta High School', false, '2022-23', 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 32, 61, true),
  ('1f44c5', 'Billabong', 'Billabong High International School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 82, true),
  ('1b4868', 'Bombay Scottish', 'Bombay Scottish School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 89, true),
  ('9d77d9', 'Bombay Scottish', 'Bombay Scottish School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 33, 0, true),
  ('81530d', 'Bombay Scottish Mahim A03', 'Bombay Scottish School, Mahim', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 18, 47, true),
  ('df7d9b', 'Cbs Rehearsal X Maths', 'CBS', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('8ca4cf', 'Champion', 'Champion', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 90, true),
  ('a53e09', 'Children''S Academy Prelim01', 'Children''s Academy', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 105, true),
  ('739266', 'Children''S Academy Ut01', 'Children''s Academy', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 15, 47, true),
  ('486d39', 'City International', 'City International', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 107, true),
  ('063ce1', 'Dhirubhai Ambani', 'Dhirubhai Ambani International School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 71, true),
  ('c133fe', 'Dhirubhai Ambani', 'Dhirubhai Ambani International School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 104, true),
  ('2914e8', 'Dps Newton', 'Delhi Public School, Newtown', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 100, true),
  ('531696', 'Ges Prelim01', 'GES', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('fe0316', 'Gokuldham Int Term01', 'Gokuldham High School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('180d2c', 'Gokuldham Premlminary', 'Gokuldham High School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 96, true),
  ('577a37', 'Gundecha', 'Gundecha Education Academy, Kandivali', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 38, 89, true),
  ('324e9b', 'Hutchings', 'Hutchings', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 40, 109, true),
  ('5d726a', 'J B Petit', 'J. B. Petit High School for Girls', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('ad2ac4', 'Jamnabai', 'Jamnabai Narsee School', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 100, true),
  ('687d45', 'St Mary Midterms', 'St Mary', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 39, 100, true),
  ('a0a5d3', 'Unknown', 'School not recorded', false, '2022-23', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 39, 77, false),
  ('089004', 'CBSE', 'CBSE board paper', true, '2022', 'Board Examination', 'X', 'Mathematics', 'CBSE', 18, 51, false),
  ('3c2b77', 'ICSE', 'ICSE board paper', true, '2022', 'Board Examination', 'X', 'Mathematics', 'ICSE', 30, 60, false),
  ('6cadb8', 'Beacon High', 'Beacon High', false, '2021-22', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 30, 54, true),
  ('1440ac', 'Dps Megacity Pre Boards 23 Mathematics', 'Delhi Public School, Megacity', false, '2021-22', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('272ab8', 'UnknownSchool', 'School not recorded', false, '2021-22', 'chapterwise', 'X', 'Mathematics', 'ICSE', 30, 60, false),
  ('ef86c1', 'UnknownSchool', 'School not recorded', false, '2021-22', 'chapterwise', 'X', 'Mathematics', 'ICSE', 25, 40, false),
  ('ebe936', 'ICSE', 'ICSE board paper', true, '2021', 'Board Examination', 'X', 'Mathematics', 'ICSE', 32, 107, false),
  ('ef2749', 'Ais Se', 'AIS SE', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('e64369', 'Anubhuti', 'Anubhuti', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 92, true),
  ('8fb800', 'Avm Juhu Icse10 Preprelim', 'Arya Vidya Mandir, Juhu', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 107, true),
  ('b389d7', 'Bai Avabai Icse10', 'Bai Avabai Framji Petit Girls’ High School', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 107, true),
  ('0b1644', 'Bssm', 'Bombay Scottish School, Mahim', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('f1ee42', 'Cnm Icse10', 'Chandulal Nanavati Vinay Mandir', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 23, 80, true),
  ('10e246', 'Cnms Mpe', 'Chandulal Nanavati Vinay Mandir', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 107, true),
  ('3a7e1c', 'Dbcs Fre', 'DBCS', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 26, 82, true),
  ('85f3a4', 'Dr Mts Pune', 'Dr Mts Pune', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 107, true),
  ('742c45', 'Gea Fpe', 'Gundecha Education Academy, Kandivali', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('ed8de4', 'Ghsjc Fpe', 'GHSJC', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('f4dc9d', 'Greenwood High Icse10 Term1 Question', 'Greenwood High International School, Bengaluru', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 102, true),
  ('9d3c19', 'Hcs', 'HCS', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 28, 93, true),
  ('b00c17', 'Hfs Powai', 'Hiranandani Foundation School, Powai', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 109, true),
  ('9985ff', 'Hfs Thane Icse10 Prel', 'Hiranandani Foundation School, Thane', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 107, true),
  ('c07ec7', 'Hyderabad Public School Pfe Ii', 'The Hyderabad Public School', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('c2e512', 'Internobilian Pie', 'Internobilian', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('64765f', 'Jamnabai Narsee Spe', 'Jamnabai Narsee School', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 104, true),
  ('6ac7ab', 'Jgs Icse10 2Ndterm', 'JGS', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 11, 50, true),
  ('3e509f', 'Lml Icse10', 'LML', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 33, 103, true),
  ('876e1d', 'Nps', 'NPS', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('63a77f', 'Nps Icse10', 'NPS', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 92, true),
  ('c60a9d', 'Pis', 'PIS', false, '2020-21', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 103, true),
  ('f7562d', 'CBSE', 'CBSE board paper', true, '2020', 'Board Examination', 'X', 'Mathematics', 'CBSE', 50, 107, false),
  ('c628be', 'ICSE', 'ICSE board paper', true, '2020', 'Board Examination', 'X', 'Mathematics', 'ICSE', 32, 104, false),
  ('405263', 'ICSE', 'ICSE board paper', true, '2020', 'Board Examination', 'X', 'Mathematics', 'ICSE', 25, 80, false),
  ('bdb81a', 'ICSE', 'ICSE board paper', true, '2020', 'Board Examination', 'X', 'Mathematics', 'ICSE', 10, 32, false),
  ('24cd75', 'Jns', 'Jamnabai Narsee School', false, '2019-20', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 55, true),
  ('cb9f45', 'Lml Icse10', 'LML', false, '2019-20', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 110, true),
  ('268a6e', 'UnknownSchool', 'School not recorded', false, '2019-20', 'chapterwise', 'X', 'Mathematics', 'ICSE', 32, 104, false),
  ('fedd3e', 'CBSE', 'CBSE board paper', true, '2019', 'Board Examination', 'X', 'Mathematics', 'CBSE', 30, 80, false),
  ('22c5bb', 'ICSE', 'ICSE board paper', true, '2019', 'Board Examination', 'X', 'Mathematics', 'ICSE', 32, 111, false),
  ('2ab95b', 'ICSE', 'ICSE board paper', true, '2019', 'Board Examination', 'X', 'Mathematics', 'ICSE', 24, 82, false),
  ('bdf81d', 'ICSE', 'ICSE board paper', true, '2019', 'Board Examination', 'X', 'Mathematics', 'ICSE', 34, 82, false),
  ('4ac516', 'CBSE', 'CBSE board paper', true, '2018-19', 'Sample Paper', 'X', 'Mathematics', 'CBSE', 41, 110, false),
  ('48d218', 'Cnms', 'Chandulal Nanavati Vinay Mandir', false, '2018-19', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 90, true),
  ('236e62', 'Orion', 'IES Orion, Dadar', false, '2018-19', 'Pre-board Examination', 'X', 'Mathematics', 'Board', 34, 90, true),
  ('46a02f', 'CBSE', 'CBSE board paper', true, '2018', 'Board Examination', 'X', 'Mathematics', 'CBSE', 18, 50, false),
  ('4a4144', 'CBSE', 'CBSE board paper', true, '2018', 'Board Examination', 'X', 'Mathematics', 'CBSE', 35, 98, false),
  ('026b8b', 'ICSE', 'ICSE board paper', true, '2018', 'Board Examination', 'X', 'Mathematics', 'ICSE', 29, 89, false),
  ('f95af9', 'ICSE', 'ICSE board paper', true, '2018', 'Board Examination', 'X', 'Mathematics', 'ICSE', 31, 90, false),
  ('617255', 'ICSE', 'ICSE board paper', true, '2018', 'Board Examination', 'X', 'Mathematics', 'ICSE', 17, 46, false),
  ('8f2711', 'CBSE', 'CBSE board paper', true, '2017-18', 'Sample Paper', 'X', 'Mathematics', 'CBSE', 31, 84, false),
  ('27d1a7', 'CBSE', 'CBSE board paper', true, '2017', 'Board Examination', 'X', 'Mathematics', 'CBSE', 28, 81, false),
  ('4e563d', 'ICSE', 'ICSE board paper', true, '2017', 'Board Examination', 'X', 'Mathematics', 'ICSE', 30, 54, false),
  ('82f87f', 'ICSE', 'ICSE board paper', true, '2017', 'Board Examination', 'X', 'Mathematics', 'ICSE', 30, 107, false),
  ('d9f288', 'CBSE', 'CBSE board paper', true, '2016-17', 'Sample Paper', 'X', 'Mathematics', 'CBSE', 31, 90, false),
  ('bcaeaa', 'CBSE', 'CBSE board paper', true, '2016', 'Board Examination', 'X', 'Mathematics', 'CBSE', 31, 90, false),
  ('3bd972', 'ICSE', 'ICSE board paper', true, '2016', 'Board Examination', 'X', 'Mathematics', 'ICSE', 29, 100, false),
  ('b2e3bc', 'CBSE', 'CBSE board paper', true, '2015-16', 'Sample Paper', 'X', 'Mathematics', 'CBSE', 31, 90, false),
  ('e62428', 'CBSE', 'CBSE board paper', true, '2015', 'Board Examination', 'X', 'Mathematics', 'CBSE', 31, 90, false),
  ('4512d3', 'ICSE', 'ICSE board paper', true, '2015', 'Board Examination', 'X', 'Mathematics', 'ICSE', 30, 103, false),
  ('f32e54', 'CBSE', 'CBSE board paper', true, '2014', 'Board Examination', 'X', 'Mathematics', 'CBSE', 33, 86, false),
  ('47e321', 'ICSE', 'ICSE board paper', true, '2014', 'Board Examination', 'X', 'Mathematics', 'ICSE', 31, 92, false),
  ('cda1ba', 'CBSE', 'CBSE board paper', true, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'CBSE', 39, 76, false),
  ('c619ef', 'Avm', 'Arya Vidya Mandir', false, NULL, 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 41, 110, true),
  ('426ab6', 'Avm', 'Arya Vidya Mandir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 78, true),
  ('7444e2', 'Avm', 'Arya Vidya Mandir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 59, true),
  ('8072a3', 'Avm 6', 'Arya Vidya Mandir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 70, true),
  ('bd500d', 'Bai Avabai Framji Petite First', 'Bai Avabai Framji Petit Girls’ High School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 73, true),
  ('a441b7', 'Bhaktivedanta 9', 'Bhaktivedanta Swami Mission School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 107, true),
  ('e0a4b7', 'Bishop Westcott', 'Bishop Westcott School, Ranchi', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 38, 54, true),
  ('f3d0ba', 'Brugesh Sir', 'Brugesh Sir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 108, false),
  ('5c5012', 'Bss', 'Bombay Scottish School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 96, true),
  ('8ef68b', 'Bss Nov19', 'Bombay Scottish School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 33, 107, true),
  ('0644aa', 'Cathedral', 'The Cathedral and John Connon School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 70, true),
  ('4c6b24', 'Cathedral And John Canon', 'The Cathedral and John Connon School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 40, 63, true),
  ('4adfbe', 'CBSE', 'CBSE board paper', true, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'CBSE', 41, 92, false),
  ('53528d', 'CBSE', 'CBSE board paper', true, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'CBSE', 40, 79, false),
  ('c2986a', 'CBSE', 'CBSE board paper', true, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'CBSE', 40, 76, false),
  ('f8dd74', 'Chandulal', 'Chandulal Nanavati Vinay Mandir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 95, true),
  ('7662e6', 'Chandulal Nanavati', 'Chandulal Nanavati Vinay Mandir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 51, true),
  ('25e6f1', 'Children''S Academy', 'Children''s Academy', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 27, 83, true),
  ('b09a8a', 'Childrens Academy S01', 'Children''s Academy', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 38, 97, true),
  ('94a98d', 'Cnms Maths', 'Chandulal Nanavati Vinay Mandir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 26, 67, true),
  ('f87bc6', 'Cnms Maths', 'Chandulal Nanavati Vinay Mandir', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 23, 67, true),
  ('07b0be', 'Dais T01', 'Dhirubhai Ambani International School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 46, true),
  ('8b6e84', 'Euroschool', 'EuroSchool', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 110, true),
  ('cd554d', 'Faps', 'FAPS', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 26, 64, true),
  ('aa5296', 'Gokuldham', 'Gokuldham High School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 100, true),
  ('0f4ee3', 'Graphs Question', 'Graphs', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 21, 58, false),
  ('4f388d', 'Gundecha', 'Gundecha Education Academy, Kandivali', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 60, true),
  ('f7b449', 'Gundecha Cpe', 'Gundecha Education Academy, Kandivali', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 91, true),
  ('64d317', 'Hare Krishna', 'Hare Krishna', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 61, true),
  ('11a9e2', 'ICSE', 'ICSE board paper', true, NULL, 'Board Examination', 'X', 'Mathematics', 'ICSE', 28, 89, false),
  ('826f8c', 'Ies Orion', 'IES Orion, Dadar', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 42, 107, true),
  ('80a02c', 'Ies Pre', 'IES', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 96, true),
  ('42e281', 'Jamnabai Narsee', 'Jamnabai Narsee School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 40, 86, true),
  ('7a3130', 'Lfs', 'LFS', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 44, true),
  ('7d00e8', 'Lilavatibai Poddar High School Unit', 'Lilavatibai Podar High School', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 12, 40, true),
  ('8d981c', 'MPBFHS', 'MPBFHS', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 110, true),
  ('0622b3', 'Nps', 'NPS', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 103, true),
  ('8850b2', 'Nsm', 'NSM', false, NULL, 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 37, 75, true),
  ('db1b34', 'Orion', 'IES Orion, Dadar', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 32, 102, true),
  ('3cb594', 'Podar Maths', 'Podar', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 31, 110, true),
  ('b4312b', 'Ppsc Prel 1 Qp20', 'PPSC', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 33, 70, true),
  ('138d4b', 'Rbs', 'RBS', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 40, 47, true),
  ('09a67e', 'Svis S01', 'Swami Vivekanand International School, Kandivali', false, NULL, 'Pre-board Examination', 'X', 'Mathematics', 'Board', 41, 107, true),
  ('b2b549', 'Swami Vivekanand', 'Swami Vivekanand International School, Kandivali', false, NULL, 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 3, 3, true),
  ('2a358e', 'Thakur International School', 'Thakur International School', false, NULL, 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 46, 121, true),
  ('99a35e', 'UnknownSchool', 'School not recorded', false, NULL, 'Annual Examination', 'X', 'Mathematics', 'ICSE', 47, 105, false),
  ('07f75d', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 110, 0, false),
  ('1be9d6', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 9, 0, false),
  ('1ff52b', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 41, 0, false),
  ('320caf', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 26, 0, false),
  ('3c98bf', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 8, 0, false),
  ('5c87d6', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 41, 73, false),
  ('8b9ffe', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 31, 0, false),
  ('bdc271', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 17, 0, false),
  ('bf807b', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 25, 0, false),
  ('d045d1', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 232, 0, false),
  ('d20e5b', 'UnknownSchool', 'School not recorded', false, NULL, 'chapterwise', 'X', 'Mathematics', 'ICSE', 73, 0, false),
  ('74c327', 'Vissanji', 'Vissanji Academy', false, NULL, 'Half Yearly Examination', 'X', 'Mathematics', 'ICSE', 38, 109, true)
on conflict (id) do update set
  school_raw = excluded.school_raw, school = excluded.school,
  is_board_paper = excluded.is_board_paper, year = excluded.year,
  exam = excluded.exam, cls = excluded.cls, subject = excluded.subject,
  board = excluded.board, question_count = excluded.question_count,
  marks = excluded.marks, has_school = excluded.has_school;

commit;
