// GENERATED by scripts/generate-blog-nav.ts -- do not edit.
//
// The footer's blog links, precomputed so that Footer.tsx does not have to
// import src/content/blog.ts, which transitively pulls the ~116KB generated
// blog-stats blob into the eager bundle on every page of the site.
//
// Regenerate with: npm run generate-blog-nav (runs automatically in prebuild).

export interface BlogNavLink {
  to: string;
  label: string;
}

export const BLOG_PATH = "/blog";

export const BLOG_FOOTER_LINKS: BlogNavLink[] = [
  {
    "to": "/blog/which-chapters-carry-the-marks",
    "label": "Maths: Which chapters carry the marks"
  },
  {
    "to": "/blog/how-kolkata-schools-set-their-papers",
    "label": "Maths: How schools set their papers"
  },
  {
    "to": "/blog/which-topics-carry-the-marks-in-history-and-civics-papers",
    "label": "History & Civics: Which topics carry the marks"
  },
  {
    "to": "/blog/how-kolkata-schools-set-their-history-and-civics-papers",
    "label": "History & Civics: How schools set their papers"
  },
  {
    "to": "/blog/how-kolkata-schools-set-their-economics-papers",
    "label": "Economics: How schools set their papers"
  },
  {
    "to": "/blog/which-topics-carry-the-marks-in-english-papers",
    "label": "English: Which topics carry the marks"
  },
  {
    "to": "/blog/how-kolkata-schools-set-their-english-papers",
    "label": "English: How schools set their papers"
  }
];
