/* GENERATED by scripts/generate-blog-stats.ts -- do not edit by hand.
 * Run `npm run generate-blog-stats` after changing data/question-bank.json.
 *
 * Every number here was counted from the question bank. Nothing is estimated,
 * rounded up for effect, or carried over from a previous version of the file.
 */

export interface ChapterStat {
  name: string;
  slug: string;
  questions: number;
  marks: number;
  papers: number;
  schools: number;
  firstYear: string | null;
  lastYear: string | null;
  averageMarks: number;
  longQuestions: number;
  shortQuestions: number;
  examTypes: Array<{ label: string; count: number }>;
  markValues: Array<{ value: number; count: number }>;
}

export interface BankTotals {
  questions: number;
  marks: number;
  papers: number;
  schools: number;
  chapters: number;
  firstYear: string | null;
  lastYear: string | null;
}

/** What the bank actually covers. Stated so no page can imply wider coverage. */
export const BANK_SCOPE = {
  subject: 'Maths',
  classLevel: '10',
  board: 'ICSE',
} as const;

export const BANK_TOTALS: BankTotals = {
  "questions": 6912,
  "marks": 15709,
  "papers": 193,
  "schools": 100,
  "chapters": 18,
  "firstYear": "2014",
  "lastYear": "2026"
};

/** Ordered by total marks, heaviest first. */
export const CHAPTER_STATS: ChapterStat[] = [
  {
    "name": "Coordinate Geometry",
    "slug": "coordinate-geometry",
    "questions": 807,
    "marks": 1826,
    "papers": 169,
    "schools": 93,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.3,
    "longQuestions": 222,
    "shortQuestions": 411,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 447
      },
      {
        "label": "Board Examination",
        "count": 205
      },
      {
        "label": "chapterwise",
        "count": 85
      },
      {
        "label": "Half Yearly Examination",
        "count": 45
      },
      {
        "label": "Sample Paper",
        "count": 15
      },
      {
        "label": "Unit Test",
        "count": 7
      },
      {
        "label": "Annual Examination",
        "count": 3
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 201
      },
      {
        "value": 2,
        "count": 52
      },
      {
        "value": 3,
        "count": 190
      },
      {
        "value": 4,
        "count": 166
      },
      {
        "value": 5,
        "count": 55
      },
      {
        "value": 6,
        "count": 2
      }
    ]
  },
  {
    "name": "Statistics",
    "slug": "statistics",
    "questions": 560,
    "marks": 1687,
    "papers": 160,
    "schools": 92,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 3,
    "longQuestions": 245,
    "shortQuestions": 237,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 367
      },
      {
        "label": "Board Examination",
        "count": 132
      },
      {
        "label": "chapterwise",
        "count": 33
      },
      {
        "label": "Half Yearly Examination",
        "count": 17
      },
      {
        "label": "Sample Paper",
        "count": 6
      },
      {
        "label": "Annual Examination",
        "count": 3
      },
      {
        "label": "Unit Test",
        "count": 2
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 91
      },
      {
        "value": 2,
        "count": 7
      },
      {
        "value": 3,
        "count": 130
      },
      {
        "value": 4,
        "count": 121
      },
      {
        "value": 5,
        "count": 36
      },
      {
        "value": 6,
        "count": 88
      }
    ]
  },
  {
    "name": "Trigonometry",
    "slug": "trigonometry",
    "questions": 665,
    "marks": 1518,
    "papers": 169,
    "schools": 88,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.3,
    "longQuestions": 193,
    "shortQuestions": 386,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 348
      },
      {
        "label": "Board Examination",
        "count": 170
      },
      {
        "label": "chapterwise",
        "count": 92
      },
      {
        "label": "Half Yearly Examination",
        "count": 20
      },
      {
        "label": "Sample Paper",
        "count": 16
      },
      {
        "label": "Unit Test",
        "count": 13
      },
      {
        "label": "Annual Examination",
        "count": 6
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 112
      },
      {
        "value": 2,
        "count": 31
      },
      {
        "value": 3,
        "count": 183
      },
      {
        "value": 4,
        "count": 171
      },
      {
        "value": 5,
        "count": 21
      },
      {
        "value": 6,
        "count": 1
      }
    ]
  },
  {
    "name": "Quadratic Equations",
    "slug": "quadratic-equations",
    "questions": 644,
    "marks": 1436,
    "papers": 174,
    "schools": 95,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.2,
    "longQuestions": 158,
    "shortQuestions": 370,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 331
      },
      {
        "label": "Board Examination",
        "count": 182
      },
      {
        "label": "chapterwise",
        "count": 78
      },
      {
        "label": "Half Yearly Examination",
        "count": 30
      },
      {
        "label": "Sample Paper",
        "count": 15
      },
      {
        "label": "Unit Test",
        "count": 6
      },
      {
        "label": "Annual Examination",
        "count": 2
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 143
      },
      {
        "value": 2,
        "count": 23
      },
      {
        "value": 3,
        "count": 199
      },
      {
        "value": 4,
        "count": 150
      },
      {
        "value": 5,
        "count": 10
      }
    ]
  },
  {
    "name": "Mensuration",
    "slug": "mensuration",
    "questions": 513,
    "marks": 1198,
    "papers": 159,
    "schools": 86,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.3,
    "longQuestions": 150,
    "shortQuestions": 268,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 279
      },
      {
        "label": "Board Examination",
        "count": 147
      },
      {
        "label": "chapterwise",
        "count": 44
      },
      {
        "label": "Sample Paper",
        "count": 22
      },
      {
        "label": "Half Yearly Examination",
        "count": 18
      },
      {
        "label": "Unit Test",
        "count": 3
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 120
      },
      {
        "value": 2,
        "count": 16
      },
      {
        "value": 3,
        "count": 141
      },
      {
        "value": 4,
        "count": 129
      },
      {
        "value": 5,
        "count": 19
      },
      {
        "value": 6,
        "count": 2
      }
    ]
  },
  {
    "name": "GST and Banking",
    "slug": "gst-and-banking",
    "questions": 504,
    "marks": 1119,
    "papers": 146,
    "schools": 94,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.2,
    "longQuestions": 120,
    "shortQuestions": 273,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 293
      },
      {
        "label": "Board Examination",
        "count": 115
      },
      {
        "label": "chapterwise",
        "count": 60
      },
      {
        "label": "Half Yearly Examination",
        "count": 36
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 102
      },
      {
        "value": 2,
        "count": 5
      },
      {
        "value": 3,
        "count": 174
      },
      {
        "value": 4,
        "count": 115
      },
      {
        "value": 5,
        "count": 5
      }
    ]
  },
  {
    "name": "Circles",
    "slug": "circles",
    "questions": 503,
    "marks": 1048,
    "papers": 156,
    "schools": 87,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.1,
    "longQuestions": 108,
    "shortQuestions": 299,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 281
      },
      {
        "label": "Board Examination",
        "count": 135
      },
      {
        "label": "chapterwise",
        "count": 59
      },
      {
        "label": "Half Yearly Examination",
        "count": 13
      },
      {
        "label": "Sample Paper",
        "count": 10
      },
      {
        "label": "Unit Test",
        "count": 3
      },
      {
        "label": "Annual Examination",
        "count": 2
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 129
      },
      {
        "value": 2,
        "count": 24
      },
      {
        "value": 3,
        "count": 143
      },
      {
        "value": 4,
        "count": 99
      },
      {
        "value": 5,
        "count": 8
      },
      {
        "value": 6,
        "count": 1
      }
    ]
  },
  {
    "name": "Arithmetic Progression",
    "slug": "arithmetic-progression",
    "questions": 379,
    "marks": 781,
    "papers": 151,
    "schools": 88,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.1,
    "longQuestions": 67,
    "shortQuestions": 215,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 203
      },
      {
        "label": "Board Examination",
        "count": 97
      },
      {
        "label": "chapterwise",
        "count": 41
      },
      {
        "label": "Half Yearly Examination",
        "count": 19
      },
      {
        "label": "Sample Paper",
        "count": 16
      },
      {
        "label": "Unit Test",
        "count": 3
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 115
      },
      {
        "value": 2,
        "count": 29
      },
      {
        "value": 3,
        "count": 110
      },
      {
        "value": 4,
        "count": 67
      },
      {
        "value": 5,
        "count": 2
      }
    ]
  },
  {
    "name": "Similarity",
    "slug": "similarity",
    "questions": 357,
    "marks": 762,
    "papers": 154,
    "schools": 87,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.1,
    "longQuestions": 90,
    "shortQuestions": 195,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 179
      },
      {
        "label": "Board Examination",
        "count": 99
      },
      {
        "label": "chapterwise",
        "count": 55
      },
      {
        "label": "Half Yearly Examination",
        "count": 13
      },
      {
        "label": "Sample Paper",
        "count": 7
      },
      {
        "label": "Unit Test",
        "count": 4
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 84
      },
      {
        "value": 2,
        "count": 17
      },
      {
        "value": 3,
        "count": 89
      },
      {
        "value": 4,
        "count": 78
      },
      {
        "value": 5,
        "count": 13
      }
    ]
  },
  {
    "name": "Ratio and Proportion",
    "slug": "ratio-and-proportion",
    "questions": 308,
    "marks": 731,
    "papers": 131,
    "schools": 87,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.4,
    "longQuestions": 75,
    "shortQuestions": 183,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 190
      },
      {
        "label": "Board Examination",
        "count": 71
      },
      {
        "label": "chapterwise",
        "count": 31
      },
      {
        "label": "Half Yearly Examination",
        "count": 16
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 49
      },
      {
        "value": 2,
        "count": 2
      },
      {
        "value": 3,
        "count": 126
      },
      {
        "value": 4,
        "count": 75
      }
    ]
  },
  {
    "name": "Factorisation and Remainder Theorem",
    "slug": "factorisation-and-remainder-theorem",
    "questions": 301,
    "marks": 689,
    "papers": 143,
    "schools": 90,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.3,
    "longQuestions": 76,
    "shortQuestions": 154,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 185
      },
      {
        "label": "Board Examination",
        "count": 80
      },
      {
        "label": "chapterwise",
        "count": 25
      },
      {
        "label": "Half Yearly Examination",
        "count": 10
      },
      {
        "label": "Sample Paper",
        "count": 1
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 70
      },
      {
        "value": 2,
        "count": 2
      },
      {
        "value": 3,
        "count": 103
      },
      {
        "value": 4,
        "count": 74
      },
      {
        "value": 5,
        "count": 2
      }
    ]
  },
  {
    "name": "Matrices",
    "slug": "matrices",
    "questions": 317,
    "marks": 663,
    "papers": 139,
    "schools": 90,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.1,
    "longQuestions": 52,
    "shortQuestions": 180,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 205
      },
      {
        "label": "Board Examination",
        "count": 75
      },
      {
        "label": "chapterwise",
        "count": 25
      },
      {
        "label": "Half Yearly Examination",
        "count": 12
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 85
      },
      {
        "value": 2,
        "count": 2
      },
      {
        "value": 3,
        "count": 122
      },
      {
        "value": 4,
        "count": 52
      }
    ]
  },
  {
    "name": "Probability",
    "slug": "probability",
    "questions": 331,
    "marks": 631,
    "papers": 157,
    "schools": 88,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 1.9,
    "longQuestions": 29,
    "shortQuestions": 216,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 189
      },
      {
        "label": "Board Examination",
        "count": 78
      },
      {
        "label": "chapterwise",
        "count": 27
      },
      {
        "label": "Half Yearly Examination",
        "count": 23
      },
      {
        "label": "Sample Paper",
        "count": 10
      },
      {
        "label": "Annual Examination",
        "count": 4
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 106
      },
      {
        "value": 2,
        "count": 33
      },
      {
        "value": 3,
        "count": 113
      },
      {
        "value": 4,
        "count": 26
      },
      {
        "value": 5,
        "count": 2
      },
      {
        "value": 6,
        "count": 1
      }
    ]
  },
  {
    "name": "Linear Inequations",
    "slug": "linear-inequations",
    "questions": 246,
    "marks": 489,
    "papers": 138,
    "schools": 92,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2,
    "longQuestions": 16,
    "shortQuestions": 159,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 144
      },
      {
        "label": "Board Examination",
        "count": 57
      },
      {
        "label": "chapterwise",
        "count": 26
      },
      {
        "label": "Half Yearly Examination",
        "count": 19
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 69
      },
      {
        "value": 2,
        "count": 2
      },
      {
        "value": 3,
        "count": 117
      },
      {
        "value": 4,
        "count": 15
      },
      {
        "value": 5,
        "count": 1
      }
    ]
  },
  {
    "name": "Constructions",
    "slug": "constructions",
    "questions": 147,
    "marks": 415,
    "papers": 107,
    "schools": 58,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.8,
    "longQuestions": 73,
    "shortQuestions": 74,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 75
      },
      {
        "label": "Board Examination",
        "count": 50
      },
      {
        "label": "chapterwise",
        "count": 16
      },
      {
        "label": "Sample Paper",
        "count": 5
      },
      {
        "label": "Half Yearly Examination",
        "count": 1
      }
    ],
    "markValues": [
      {
        "value": 3,
        "count": 39
      },
      {
        "value": 4,
        "count": 68
      },
      {
        "value": 5,
        "count": 4
      },
      {
        "value": 6,
        "count": 1
      }
    ]
  },
  {
    "name": "Shares and Dividends",
    "slug": "shares-and-dividends",
    "questions": 78,
    "marks": 186,
    "papers": 49,
    "schools": 22,
    "firstYear": "2014",
    "lastYear": "2026",
    "averageMarks": 2.4,
    "longQuestions": 15,
    "shortQuestions": 43,
    "examTypes": [
      {
        "label": "Board Examination",
        "count": 43
      },
      {
        "label": "Pre-board Examination",
        "count": 34
      },
      {
        "label": "chapterwise",
        "count": 1
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 21
      },
      {
        "value": 3,
        "count": 35
      },
      {
        "value": 4,
        "count": 15
      }
    ]
  },
  {
    "name": "Geometric Progression",
    "slug": "geometric-progression",
    "questions": 45,
    "marks": 118,
    "papers": 37,
    "schools": 20,
    "firstYear": "2018",
    "lastYear": "2026",
    "averageMarks": 2.6,
    "longQuestions": 10,
    "shortQuestions": 29,
    "examTypes": [
      {
        "label": "Board Examination",
        "count": 22
      },
      {
        "label": "Pre-board Examination",
        "count": 21
      },
      {
        "label": "Annual Examination",
        "count": 1
      },
      {
        "label": "chapterwise",
        "count": 1
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 6
      },
      {
        "value": 3,
        "count": 24
      },
      {
        "value": 4,
        "count": 10
      }
    ]
  },
  {
    "name": "Loci",
    "slug": "loci",
    "questions": 6,
    "marks": 8,
    "papers": 6,
    "schools": 6,
    "firstYear": "2022-23",
    "lastYear": "2025",
    "averageMarks": 1.3,
    "longQuestions": 1,
    "shortQuestions": 2,
    "examTypes": [
      {
        "label": "Pre-board Examination",
        "count": 5
      },
      {
        "label": "Board Examination",
        "count": 1
      }
    ],
    "markValues": [
      {
        "value": 1,
        "count": 3
      },
      {
        "value": 5,
        "count": 1
      }
    ]
  }
];

export const CHAPTER_BY_SLUG: Record<string, ChapterStat> = Object.fromEntries(
  CHAPTER_STATS.map((c) => [c.slug, c]),
);
