/**
 * Display order for subjects on the Browse page (dropdown + advanced filters).
 * Subjects not in this list appear at the end, in their original order.
 */
export const SUBJECT_DISPLAY_ORDER = [
  'Maths',
  'English',
  'Accounts',
  'Economics',
  'Commerce',
  'Science',
  'Physics',
  'Chemistry',
  'Biology',
  'History & Civics',
  'Geography',
  'Social Studies',
  'Computers',
  'Hindi',
  'Business Studies',
  'Sociology',
  'Political Science',
  'Psychology',
  'Legal Studies',
  'Home Science',
  'Environmental Science',
  'Bengali',
  'Sanskrit',
  'Drawing & Painting',
  'JEE',
  'CA',
  'NEET',
  'CAT',
  'SAT',
  'NMAT',
  'AP',
  'ACT',
  'CLAT',
];
