#!/usr/bin/env tsx
/**
 * Decides which locality x subject pages exist and writes
 * src/content/locality-pages.generated.ts.
 *
 * Runs in `prebuild`, before vite build, so the client bundle knows the same
 * list (and the same teacher counts, which the page title carries) that the
 * prerender and the sitemap use. A count only appears in a title if a real
 * teacher query produced it, never a hand-typed number.
 *
 * Fails loudly on missing credentials or an unreachable table, like the
 * sitemap generator: nobody here can read Vercel's build logs, so a red deploy
 * is the only signal that reaches anyone.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';

import {
  computeLocalityCombos,
  localityDescription,
  localityFacts,
  teachersFor,
  MIN_LOCALITY_TEACHERS,
} from '../src/lib/locality';
import { fetchLocalityTeachers } from './locality-data';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
config({ path: path.join(__dirname, '..', '.env') });

const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'content', 'locality-pages.generated.ts');

function fail(message: string): never {
  console.error(`\nLOCALITY PAGES FAILED: ${message}`);
  console.error('Refusing to continue with a stale or partial locality list.\n');
  process.exit(1);
}

async function main(): Promise<void> {
  const url = process.env.VITE_SUPABASE_URL || '';
  const key = process.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
  if (!url || !key) fail('Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY');

  const teachers = await fetchLocalityTeachers(createClient(url, key), fail);
  if (teachers.length === 0) fail('no teachers readable');

  const combos = computeLocalityCombos(teachers);
  /* The description is generated here, once, because it names the real board
     mix of these teachers. The client and the prerender both read this same
     string, so the two can never describe the page differently. */
  const rows = combos
    .map((c) => {
      const description = localityDescription(
        c.subjectLabel,
        c.area,
        c.count,
        localityFacts(teachersFor(teachers, c.subjectPath, c.area)),
      );
      return `  { path: '${c.path}', subjectPath: '${c.subjectPath}', area: '${c.area}', count: ${c.count}, description: ${JSON.stringify(description)} },`;
    })
    .join('\n');

  const body = `/**
 * GENERATED by scripts/generate-locality-pages.ts (npm run generate-locality-pages).
 * Do not edit by hand: it is rewritten on every build.
 *
 * Every (subject, area) pair with at least ${MIN_LOCALITY_TEACHERS} real, published, unpaused teachers.
 */

export interface LocalityPageEntry {
  path: string;
  subjectPath: string;
  area: string;
  count: number;
  description: string;
}

export const LOCALITY_PAGES: LocalityPageEntry[] = [
${rows}
];
`;
  fs.writeFileSync(OUTPUT_PATH, body, 'utf8');
  console.log(`Locality pages: ${combos.length} of the (subject, area) pairs have ${MIN_LOCALITY_TEACHERS}+ teachers (${teachers.length} teachers read)`);
  for (const c of combos) console.log(`   ${c.path}  (${c.count})`);
}

main().catch((err) => fail(String(err)));
