#!/usr/bin/env tsx
/**
 * Emit the footer's blog link list as a standalone module.
 *
 * Footer.tsx needs eight links: slug and short title for the non-topic
 * articles. It got them by importing BLOG_ARTICLES from src/content/blog.ts --
 * which derives them at module load from BLOG_SUBJECTS in blog-stats.ts, a
 * generated ~116KB blob of per-chapter counts.
 *
 * Because the Footer renders on every page, that blob was pulled into the
 * eager bundle: ~45KB minified inside index-*.js, about a tenth of the main
 * chunk, on every single page load, so a visitor who never opens /blog still
 * downloaded and parsed every chapter statistic for every subject.
 *
 * Splitting the imports cannot fix it, because BLOG_ARTICLES genuinely needs
 * the stats -- each article's title and description interpolate real counts.
 * What the footer needs, though, is only the fields that are static literals.
 * So this precomputes those at build time.
 *
 * Generated from blog.ts rather than hand-maintained, deliberately: a second
 * hand-written list of article slugs would drift the first time someone adds a
 * subject, and drift silently, because nothing would fail.
 *
 * Runs in prebuild, alongside the sitemap.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { BLOG_ARTICLES, BLOG_PATH } from '../src/content/blog';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OUTPUT = path.join(__dirname, '..', 'src', 'content', 'blog-nav.ts');

/* Exactly the shape Footer built inline, so the component's own logic does not
   move -- only where the data comes from. */
const links = BLOG_ARTICLES
  .filter((a) => a.kind !== 'topic')
  .map((a) => ({
    to: `${BLOG_PATH}/${a.slug}`,
    label: `${a.subject === 'Mathematics' ? 'Maths' : a.subject}: ${a.shortTitle}`,
  }));

if (links.length === 0) {
  console.error('\nBLOG NAV FAILED: no non-topic articles found in BLOG_ARTICLES.');
  process.exit(1);
}

const body = `// GENERATED by scripts/generate-blog-nav.ts -- do not edit.
//
// The footer's blog links, precomputed so that Footer.tsx does not have to
// import src/content/blog.ts, which transitively pulls the ~116KB generated
// blog-stats blob into the eager bundle on every page of the site.
//
// Regenerate with: npm run generate-blog-nav (runs automatically in prebuild).

export interface BlogNavLink {
  to: string;
  label: string;
}

export const BLOG_PATH = ${JSON.stringify(BLOG_PATH)};

export const BLOG_FOOTER_LINKS: BlogNavLink[] = ${JSON.stringify(links, null, 2)};
`;

fs.writeFileSync(OUTPUT, body, 'utf8');
console.log(`Blog nav: ${links.length} footer links -> src/content/blog-nav.ts`);
