#!/usr/bin/env tsx
/**
 * Record the intrinsic pixel size of every paper figure.
 *
 * BankPaper renders these with `max-h-[300px] w-auto` and no width/height
 * attributes, so the browser cannot reserve space for them until the bytes
 * arrive. On a question-heavy maths paper that is dozens of images popping in
 * and shoving the text down as the reader is trying to read it -- the worst
 * kind of layout shift, because it happens continuously while scrolling rather
 * than once at load.
 *
 * Attributes fix that without touching the images: given width and height, the
 * browser knows the aspect ratio immediately and reserves a correctly shaped
 * box, while the CSS still decides the rendered size.
 *
 * Reads the dimensions straight out of the WebP headers rather than adding an
 * image library. sharp is the obvious tool and is a native binary; a native
 * dependency that fails to install breaks the Vercel build, and nobody on this
 * team can read those logs to find out why. Header parsing is ~40 lines, has
 * no install step, and cannot fail at deploy time.
 *
 * NOT solved here: the files are still full size. 25MB across 1,023 figures,
 * the largest 312KB, all painted at most 300px tall. Fixing that needs real
 * resizing (sharp at build time, or an image CDN) and should be done
 * deliberately, with someone able to watch the build.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FIGURES_DIR = path.join(__dirname, '..', 'public', 'paper-figures');
const OUTPUT = path.join(__dirname, '..', 'src', 'content', 'figure-dimensions.ts');

/** Intrinsic size from a WebP header. Null when the format is not recognised. */
function webpSize(buf: Buffer): { w: number; h: number } | null {
  if (buf.length < 30) return null;
  if (buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WEBP') return null;

  const fourCC = buf.toString('ascii', 12, 16);

  // Extended format: 24-bit little-endian canvas size, stored minus one.
  if (fourCC === 'VP8X') {
    const w = 1 + (buf[24] | (buf[25] << 8) | (buf[26] << 16));
    const h = 1 + (buf[27] | (buf[28] << 8) | (buf[29] << 16));
    return { w, h };
  }

  // Lossy: 14-bit dimensions after the 3-byte start code and 'VP8 ' frame tag.
  if (fourCC === 'VP8 ') {
    return { w: buf.readUInt16LE(26) & 0x3fff, h: buf.readUInt16LE(28) & 0x3fff };
  }

  // Lossless: 14-bit each, bit-packed across four bytes, stored minus one.
  if (fourCC === 'VP8L' && buf[20] === 0x2f) {
    const b = buf.readUInt32LE(21);
    return { w: 1 + (b & 0x3fff), h: 1 + ((b >> 14) & 0x3fff) };
  }

  return null;
}

if (!fs.existsSync(FIGURES_DIR)) {
  console.warn('   No public/paper-figures directory; skipping figure dimensions.');
  process.exit(0);
}

const dims: Record<string, [number, number]> = {};
let unreadable = 0;

for (const name of fs.readdirSync(FIGURES_DIR)) {
  if (!name.toLowerCase().endsWith('.webp')) continue;
  const full = path.join(FIGURES_DIR, name);
  // Only the header is needed, so read 40 bytes rather than 300KB.
  const fd = fs.openSync(full, 'r');
  const buf = Buffer.alloc(40);
  fs.readSync(fd, buf, 0, 40, 0);
  fs.closeSync(fd);

  const size = webpSize(buf);
  if (size && size.w > 0 && size.h > 0) dims[name] = [size.w, size.h];
  else unreadable++;
}

const count = Object.keys(dims).length;
if (count === 0) {
  console.error('\nFIGURE DIMENSIONS FAILED: no readable WebP headers found.');
  process.exit(1);
}

const body = `// GENERATED by scripts/generate-figure-dimensions.ts -- do not edit.
//
// Intrinsic pixel size of each paper figure, so the reader can set width and
// height on the <img> and reserve correctly shaped space before the bytes
// arrive. Without these, a question-heavy paper shifts its text continuously
// as figures load while the reader is scrolling through it.
//
// Regenerate with: npm run generate-figure-dimensions (runs in prebuild).

export const FIGURE_DIMENSIONS: Record<string, [number, number]> = ${JSON.stringify(dims)};
`;

fs.writeFileSync(OUTPUT, body, 'utf8');
console.log(`Figure dimensions: ${count} figures${unreadable ? `, ${unreadable} unreadable` : ''} -> src/content/figure-dimensions.ts`);
