/**
 * Derives the blog's chapter statistics from the question bank.
 *
 * The blog's whole claim is that its numbers are counted, not asserted: "GST
 * and Banking carried 1,119 marks across 193 papers" is worth reading because
 * nobody else has counted it, and it is worth trusting because this script is
 * the only thing that produces it. Nothing in src/content/blog-stats.ts is
 * typed by hand.
 *
 *   npm run generate-blog-stats
 *
 * Reads data/question-bank.json (the source of record, deliberately outside
 * public/ so it is never served) and writes a generated TS module. Question
 * TEXT is never read here -- only the metadata fields -- so the "question-paper
 * text is never altered" rule cannot be violated by this path.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(ROOT, 'data', 'question-bank.json');
const OUTPUT = path.join(ROOT, 'src', 'content', 'blog-stats.ts');

/** Only the metadata fields. `t` (question text) is deliberately not read. */
interface BankQuestion {
  p?: string;
  m?: number | null;
  c?: string | null;
  s?: string | null;
  y?: string | null;
  e?: string | null;
  k?: string | null;
  ty?: string | null;
}

/* The bank carries a few non-year labels in `y` (e.g. "year-unknown (2)").
   A plain string sort ranks those above every real year, which put
   "year-unknown (2)" in the blog as the latest year covered. Only values that
   look like a year, or a year-range opening on one, count towards a range. */
const YEAR_RE = /^\d{4}(-\d{2})?$/;
const isYear = (v: string | null | undefined): v is string => !!v && YEAR_RE.test(v);

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function main() {
  if (!fs.existsSync(SOURCE)) {
    console.error(`\n[blog-stats] ${path.relative(ROOT, SOURCE)} not found — nothing written.`);
    process.exit(1);
  }

  const rows: BankQuestion[] = JSON.parse(fs.readFileSync(SOURCE, 'utf-8'));

  const byChapter = new Map<
    string,
    {
      questions: number;
      marks: number;
      papers: Set<string>;
      schools: Set<string>;
      years: Set<string>;
      examTypes: Map<string, number>;
      markValues: Map<number, number>;
      long: number;
      short: number;
    }
  >();

  const allPapers = new Set<string>();
  const allSchools = new Set<string>();
  const allYears = new Set<string>();
  let totalMarks = 0;

  for (const q of rows) {
    if (q.p) allPapers.add(q.p);
    if (q.s) allSchools.add(q.s);
    if (isYear(q.y)) allYears.add(q.y);
    totalMarks += q.m ?? 0;

    const chapter = q.c;
    if (!chapter) continue;

    let e = byChapter.get(chapter);
    if (!e) {
      e = {
        questions: 0,
        marks: 0,
        papers: new Set(),
        schools: new Set(),
        years: new Set(),
        examTypes: new Map(),
        markValues: new Map(),
        long: 0,
        short: 0,
      };
      byChapter.set(chapter, e);
    }

    e.questions += 1;
    e.marks += q.m ?? 0;
    if (q.p) e.papers.add(q.p);
    if (q.s) e.schools.add(q.s);
    if (isYear(q.y)) e.years.add(q.y);
    if (q.e) e.examTypes.set(q.e, (e.examTypes.get(q.e) ?? 0) + 1);
    if (typeof q.m === 'number' && q.m > 0) {
      e.markValues.set(q.m, (e.markValues.get(q.m) ?? 0) + 1);
    }
    if (q.ty === 'long') e.long += 1;
    else if (q.ty === 'short') e.short += 1;
  }

  const chapters = [...byChapter.entries()]
    .map(([name, e]) => ({
      name,
      slug: slugify(name),
      questions: e.questions,
      marks: e.marks,
      papers: e.papers.size,
      schools: e.schools.size,
      /* Year labels in the bank are a mix of "2019" and "2019-20". Sorting the
         raw strings is enough to bound the range because both forms start with
         the opening year. */
      firstYear: [...e.years].sort()[0] ?? null,
      lastYear: [...e.years].sort().slice(-1)[0] ?? null,
      averageMarks: e.questions ? Math.round((e.marks / e.questions) * 10) / 10 : 0,
      longQuestions: e.long,
      shortQuestions: e.short,
      examTypes: [...e.examTypes.entries()]
        .sort((a, b) => b[1] - a[1])
        .map(([label, count]) => ({ label, count })),
      markValues: [...e.markValues.entries()]
        .sort((a, b) => a[0] - b[0])
        .map(([value, count]) => ({ value, count })),
    }))
    .sort((a, b) => b.marks - a.marks);

  const years = [...allYears].sort();

  const banner = `/* GENERATED by scripts/generate-blog-stats.ts -- do not edit by hand.
 * Run \`npm run generate-blog-stats\` after changing data/question-bank.json.
 *
 * Every number here was counted from the question bank. Nothing is estimated,
 * rounded up for effect, or carried over from a previous version of the file.
 */`;

  const out = `${banner}

export interface ChapterStat {
  name: string;
  slug: string;
  questions: number;
  marks: number;
  papers: number;
  schools: number;
  firstYear: string | null;
  lastYear: string | null;
  averageMarks: number;
  longQuestions: number;
  shortQuestions: number;
  examTypes: Array<{ label: string; count: number }>;
  markValues: Array<{ value: number; count: number }>;
}

export interface BankTotals {
  questions: number;
  marks: number;
  papers: number;
  schools: number;
  chapters: number;
  firstYear: string | null;
  lastYear: string | null;
}

/** What the bank actually covers. Stated so no page can imply wider coverage. */
export const BANK_SCOPE = {
  subject: 'Maths',
  classLevel: '10',
  board: 'ICSE',
} as const;

export const BANK_TOTALS: BankTotals = ${JSON.stringify(
    {
      questions: rows.length,
      marks: totalMarks,
      papers: allPapers.size,
      schools: allSchools.size,
      chapters: chapters.length,
      firstYear: years[0] ?? null,
      lastYear: years[years.length - 1] ?? null,
    },
    null,
    2,
  )};

/** Ordered by total marks, heaviest first. */
export const CHAPTER_STATS: ChapterStat[] = ${JSON.stringify(chapters, null, 2)};

export const CHAPTER_BY_SLUG: Record<string, ChapterStat> = Object.fromEntries(
  CHAPTER_STATS.map((c) => [c.slug, c]),
);
`;

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, out, 'utf-8');

  console.log(
    `[blog-stats] ${chapters.length} chapters from ${allPapers.size} papers ` +
      `(${rows.length} questions, ${allSchools.size} schools) -> ${path.relative(ROOT, OUTPUT)}`,
  );
}

main();
