#!/usr/bin/env tsx
/**
 * Emits a self-contained SQL file that creates the bank tables and loads every
 * paper and question into them.
 *
 * This exists so the import needs no service-role key and no script runner:
 * open the file, run it, done. It is the same data scripts/import-bank.ts
 * writes, by a different road.
 *
 * On byte-exactness. Question text is full of LaTeX, so it is full of
 * backslashes. The file sets standard_conforming_strings explicitly rather
 * than trusting the session default, which is what decides whether '\frac'
 * means \frac or an escape sequence. With it on, the only character needing
 * treatment is the single quote, and it is doubled. Nothing else is touched.
 *
 * Idempotent: every INSERT carries ON CONFLICT DO UPDATE, so running it twice
 * repairs rather than duplicates, and running it against a half-loaded table
 * finishes the job.
 *
 * Writes:
 *   supabase/bank-import.sql        one file, for psql
 *   supabase/bank/NN-*.sql          the same thing in editor-sized pieces
 *
 *   npm run generate-bank-sql
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

import { papersOf, hasYear, type BankQuestion } from '../src/lib/question-bank';
import { schoolLabel, isBoardPaper, hasSchool } from './school-names';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BANK_PATH = path.join(__dirname, '..', 'public', 'question-bank.json');
const OUT_FILE = path.join(__dirname, '..', 'supabase', 'bank-import.sql');
const OUT_DIR = path.join(__dirname, '..', 'supabase', 'bank');

/** A single-quoted SQL literal. Doubling the quote is the whole escape. */
const lit = (v: string | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : `'${v.replace(/'/g, "''")}'`;
const num = (v: number | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : String(v);
const bool = (v: boolean): string => (v ? 'true' : 'false');
const arr = (v: string[] | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : `array[${v.map(lit).join(', ')}]::text[]`;

const SCHEMA = `-- =====================================================================
-- Shikshaq question bank: schema + data
--
-- Creates bank_papers and bank_questions, their policies, and loads all
-- papers and questions. Safe to run more than once.
--
-- Generated by scripts/generate-bank-sql.ts. Do not hand-edit; regenerate.
-- =====================================================================

set standard_conforming_strings = on;

begin;

create table if not exists public.bank_papers (
  id             text primary key,
  school_raw     text,
  school         text        not null,
  is_board_paper boolean     not null default false,
  year           text,
  exam           text,
  cls            text        not null default 'X',
  subject        text        not null default 'Mathematics',
  board          text        not null default 'ICSE',
  question_count integer     not null default 0,
  marks          integer     not null default 0,
  is_published   boolean     not null default true,
  has_school     boolean     not null default true,
  created_at     timestamptz not null default now()
);

create table if not exists public.bank_questions (
  id       text primary key,
  paper_id text    not null references public.bank_papers (id) on delete cascade,
  ord      integer not null,
  number   text,
  body     text    not null,
  marks    integer,
  chapter  text,
  qtype    text,
  page     integer,
  figure   text,
  options  text[],
  unique (paper_id, ord)
);

create index if not exists bank_questions_paper_idx  on public.bank_questions (paper_id, ord);
create index if not exists bank_papers_school_idx    on public.bank_papers (school);
create index if not exists bank_papers_year_idx      on public.bank_papers (year desc);
create index if not exists bank_papers_published_idx on public.bank_papers (is_published) where is_published;
create index if not exists bank_papers_has_school_idx on public.bank_papers (has_school) where has_school;

alter table public.bank_papers    enable row level security;
alter table public.bank_questions enable row level security;

-- Published papers are the public library: anyone may read, nobody but an
-- admin may write. Dropped first so re-running does not fail on the policy
-- already existing.
drop policy if exists "published papers are public" on public.bank_papers;
create policy "published papers are public"
  on public.bank_papers for select to anon, authenticated
  using (is_published);

drop policy if exists "questions of published papers are public" on public.bank_questions;
create policy "questions of published papers are public"
  on public.bank_questions for select to anon, authenticated
  using (exists (select 1 from public.bank_papers p
                  where p.id = bank_questions.paper_id and p.is_published));

drop policy if exists "admins write papers" on public.bank_papers;
create policy "admins write papers"
  on public.bank_papers for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins write questions" on public.bank_questions;
create policy "admins write questions"
  on public.bank_questions for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

revoke all on public.bank_papers    from anon, authenticated;
revoke all on public.bank_questions from anon, authenticated;
grant select on public.bank_papers    to anon, authenticated;
grant select on public.bank_questions to anon, authenticated;
grant insert, update, delete on public.bank_papers    to authenticated;
grant insert, update, delete on public.bank_questions to authenticated;
`;

function main() {
  if (!fs.existsSync(BANK_PATH)) {
    console.error(`Question bank not found at ${BANK_PATH}`);
    process.exit(1);
  }

  const bank: BankQuestion[] = JSON.parse(fs.readFileSync(BANK_PATH, 'utf-8'));
  const papers = papersOf(bank);

  /* ---- papers ---------------------------------------------------------- */
  const paperValues = papers.map((p) => {
    const cols = [
      lit(p.id),
      lit(p.school ?? null),
      lit(schoolLabel(p.school)),
      bool(isBoardPaper(p.school)),
      lit(hasYear(p.year) ? p.year : null),
      lit(p.exam || null),
      lit(p.cls || 'X'),
      lit(p.subject),
      lit(p.board),
      num(p.questionCount),
      num(p.marks),
      bool(hasSchool(p.school)),
    ];
    return `  (${cols.join(', ')})`;
  });

  const papersSql =
    `-- ${papers.length} papers\n` +
    `insert into public.bank_papers\n` +
    `  (id, school_raw, school, is_board_paper, year, exam, cls, subject, board,\n` +
    `   question_count, marks, has_school)\n` +
    `values\n${paperValues.join(',\n')}\n` +
    `on conflict (id) do update set\n` +
    `  school_raw = excluded.school_raw, school = excluded.school,\n` +
    `  is_board_paper = excluded.is_board_paper, year = excluded.year,\n` +
    `  exam = excluded.exam, cls = excluded.cls, subject = excluded.subject,\n` +
    `  board = excluded.board, question_count = excluded.question_count,\n` +
    `  marks = excluded.marks, has_school = excluded.has_school;\n`;

  /* ---- questions ------------------------------------------------------- */
  const seen = new Map<string, number>();
  const questionValues = bank.map((r) => {
    const ord = seen.get(r.p) ?? 0;
    seen.set(r.p, ord + 1);
    const cols = [
      lit(r.i),
      lit(r.p),
      num(ord),
      lit(r.n ?? null),
      lit(r.t), // verbatim
      num(r.m ?? null),
      lit(r.c ?? null),
      lit(r.ty ?? null),
      num(r.pg ?? null),
      lit(r.f ?? null),
      arr(r.o ?? null),
    ];
    return `  (${cols.join(', ')})`;
  });

  const CHUNK = 500;
  const questionChunks: string[] = [];
  for (let i = 0; i < questionValues.length; i += CHUNK) {
    const slice = questionValues.slice(i, i + CHUNK);
    questionChunks.push(
      `-- questions ${i + 1}-${i + slice.length} of ${questionValues.length}\n` +
        `insert into public.bank_questions\n` +
        `  (id, paper_id, ord, number, body, marks, chapter, qtype, page, figure, options)\n` +
        `values\n${slice.join(',\n')}\n` +
        `on conflict (id) do update set\n` +
        `  paper_id = excluded.paper_id, ord = excluded.ord, number = excluded.number,\n` +
        `  body = excluded.body, marks = excluded.marks, chapter = excluded.chapter,\n` +
        `  qtype = excluded.qtype, page = excluded.page, figure = excluded.figure,\n` +
        `  options = excluded.options;\n`,
    );
  }

  const VERIFY = `
commit;

-- Expect ${papers.length} papers and ${bank.length} questions.
select
  (select count(*) from public.bank_papers)    as papers,
  (select count(*) from public.bank_questions) as questions,
  (select count(*) from public.bank_papers where has_school)     as school_papers,
  (select count(*) from public.bank_papers where is_board_paper) as board_papers,
  (select count(distinct school) from public.bank_papers where has_school) as distinct_schools;
`;

  /* ---- write ----------------------------------------------------------- */
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(
    OUT_FILE,
    [SCHEMA, papersSql, ...questionChunks, VERIFY].join('\n'),
    'utf-8',
  );

  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const pieces: [string, string][] = [
    ['00-schema.sql', `${SCHEMA}\ncommit;\n`],
    ['01-papers.sql', `set standard_conforming_strings = on;\nbegin;\n\n${papersSql}\ncommit;\n`],
    ...questionChunks.map((c, i): [string, string] => [
      `${String(i + 2).padStart(2, '0')}-questions.sql`,
      `set standard_conforming_strings = on;\nbegin;\n\n${c}\ncommit;\n`,
    ]),
    ['99-verify.sql', VERIFY.replace('commit;\n', '')],
  ];
  pieces.forEach(([name, body]) => fs.writeFileSync(path.join(OUT_DIR, name), body, 'utf-8'));

  const kb = (p: string) => (fs.statSync(p).size / 1024).toFixed(0);
  console.log(`bank-import.sql   ${kb(OUT_FILE)} KB  (${papers.length} papers, ${bank.length} questions)`);
  console.log(`supabase/bank/    ${pieces.length} files, largest ${
    Math.max(...pieces.map(([n]) => Number(kb(path.join(OUT_DIR, n)))))
  } KB`);
}

main();
