/**
 * Writes supabase/stage-english-source-pdf.sql: the printed-paper file name
 * for every English paper, staged into audit_papers.meta_source.source_pdf.
 *
 * Why: the admin paper edit page shows the source PDF's file name (owner,
 * 2026-09-28: "skip the pdf link, just have the pdf name atleast").
 * admin_paper_draft() (20260928230000) reads it from
 * meta_source->>'source_pdf', else from the end of audit_papers.pdf_path.
 * Mathematics, History & Civics and Economics carry pdf_path. English does
 * not: its 914 live_copy papers came from the W14 release, which records the
 * file in papers[].paper, keyed by paper_id = bank_papers.id. Nothing in the
 * database had it, so it is staged here.
 *
 * Writes only audit_papers (the audit copy), never bank_*. Merges into
 * meta_source with ||, so the rescue copies' role/release keys are kept.
 * Idempotent. This script does not connect to anything: it writes a SQL file
 * that a person reviews and runs in the Supabase SQL editor.
 *
 *   npx tsx scripts/stage-english-source-pdf.ts [path/to/english_question_bank_gated.json]
 *
 * Default input: the UnlimitedOCR release on the owner's machine.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const DEFAULT_INPUT =
  'C:/Users/kanis/Desktop/Code/UnlimitedOCR/auditor/data/english_release/english_question_bank_gated.json';
const OUTPUT = 'supabase/stage-english-source-pdf.sql';

interface ReleasePaper {
  paper_id?: string;
  paper?: string;
}

const input = process.argv[2] ?? DEFAULT_INPUT;
const bank = JSON.parse(readFileSync(input, 'utf8')) as { metadata?: { release?: string }; papers?: ReleasePaper[] };
const papers = (bank.papers ?? []).filter(
  (p): p is Required<ReleasePaper> => typeof p.paper_id === 'string' && typeof p.paper === 'string' && p.paper.trim() !== '',
);

const ids = new Set<string>();
for (const p of papers) {
  if (ids.has(p.paper_id)) throw new Error(`paper_id ${p.paper_id} appears twice in the release`);
  ids.add(p.paper_id);
}

/** A SQL string literal. Standard strings: only the quote needs doubling. */
const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
/** File name only, never a folder path. */
const fileName = (s: string) => s.split(/[\\/]/).pop()!.trim();

const values = papers
  .map((p) => `  (${lit(p.paper_id)}, ${lit(fileName(p.paper))})`)
  .join(',\n');

const sql = `-- Generated by scripts/stage-english-source-pdf.ts from
--   ${fileName(input)}${bank.metadata?.release ? ` (release ${bank.metadata.release})` : ''}
-- NOT a migration. Review, then run once in the Supabase SQL editor.
--
-- Stages the printed-paper file name of ${papers.length} English papers into
-- audit_papers.meta_source.source_pdf, for the admin paper edit page
-- (admin_paper_draft(), 20260928230000). Writes the audit copies only
-- (source = 'live_copy', subject English); bank_* is not touched. Merges
-- with ||, so existing meta_source keys stay. Safe to re-run.

begin;

with src(live_bank_paper_id, source_pdf) as (values
${values}
)
update public.audit_papers a
set meta_source = coalesce(a.meta_source, '{}'::jsonb) || jsonb_build_object('source_pdf', src.source_pdf)
from src
where a.source = 'live_copy'
  and a.subject = 'English'
  and a.live_bank_paper_id = src.live_bank_paper_id
  and (a.meta_source ->> 'source_pdf') is distinct from src.source_pdf;

-- Expect every English live_copy paper named (main and rescue copies):
select count(*) filter (where meta_source ? 'source_pdf') as named,
       count(*) as english_live_copies
from public.audit_papers
where source = 'live_copy' and subject = 'English';

commit;
`;

writeFileSync(OUTPUT, sql);
console.log(`Wrote ${OUTPUT}: ${papers.length} English papers.`);
